FROM python:3.10

SHELL ["/bin/bash", "-c"]

ONBUILD WORKDIR /app

ONBUILD COPY . .

ONBUILD RUN wget https://raw.githubusercontent.com/CT075/PyFunge/master/befunge_interpreter.py

CMD ["python3", "befunge_interpreter.py", "app/main.bf"]